name: dslskimage
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - scikit-image
  - pandas
  - matplotlib
  - napari
  - pyqt
  - seaborn
  - pip
  - pip:
      - bioio
      - bioio-czi
      - microfilm
      - spectral
      - trackpy